### ISSUE TITLE
Cnext Observation -- Questionable Pull  as VISIT_OCCURRENCE_ID

### ISSUE THREAD

**Issue by isangil** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#103]
I think there is a mistake pulling Tumor.FK1 as visit-occurrence-id, as tumor fk1 corresponds to the patient.uk, not the hospital related visit.

Here is the code excerpt that I find problematic - 

`
SELECT .....blahblah...

,ISNULL(rsSource.fk1,'') AS VISIT_OCCURRENCE_ID 

....

   FROM xxxxx.Tumor rsSource

`

**Comment by lvarnedoe** [comment]
This is discussed in Issue #59. VISIT_OCCURRENCE_ID is coming from different sources in various cnext scripts.

**Comment by markmayer** [comment]
I think In VISIT_OCCURRENCE the VISIT_OCCURRENCE_ID should come from TUM.UK which is the JOIN to the Hospital.fk2 which would be the hospital related visit. To be consistent and to link all the other scripts back to this visit, any occurrence of VISIT_OCCURRENCE_ID should also come from the same source (TUM.uk).

**Comment by isangil** [comment]
is this fixed @lvarnedoe ?

**Comment by lvarnedoe** [comment]
No, not yet. I sent you an email asking your take on it.

**Comment by lvarnedoe** [comment]
This has been fixed in issue #103
