### ISSUE TITLE
Cnext: person.   SOURCE_PK and PERSON_ID in the context of this extract should match but dont.

### ISSUE THREAD

**Issue by isangil** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#110]
Looks like the value placed in SOURCE_PK is just a ROWNUM counter.   On behalf of Kevin D.

**Comment by lvarnedoe** [comment]
Hi Inigo - this will be addressed by another issue I opened where I discussed how person_id is different in different scripts. I am changing it to be the Patient table's UK in all scripts.

**Comment by lvarnedoe** [comment]
I can't find the issue. I thought I had opened one. PERSON_ID is pulled from various sources in the different cnext scripts and should be consistent across the board. Mark and Kevin agreed and you and I discussed using the Patient table's UK for the value. I'm changing it in the scripts as I go through them.

**Comment by lvarnedoe** [comment]
I found it. It's #66.

**Comment by lvarnedoe** [comment]
completed the changed to the person script on this issue #110
