### ISSUE TITLE
(High) Mosaiq.Visit_Occurrence contains duplicate rows

### ISSUE THREAD

**Issue by isangil** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#16]
Currently the derivatives built for the Mosaiq-to-OMOP CDM lack a proper primary key, since these are just exports. Since these are actually staged in transient DBs, there may be a need for indexing the records, and thus maintain a proper PK.  We may adapt several tables to reflect this initiative

**Comment by KJDonovan-RS21** [comment]
SELECT COUNT(*) FROM
MQ_VISIT_OCCURRENCE WHERE SOURCE_PK IN (
SELECT SOURCE_PK FROM MQ_VISIT_OCCURRENCE
GROUP BY SOURCE_PK HAVING COUNT(*)>1)

**Comment by isangil** [comment]
addressed with Max( on modified date)

**Comment by isangil** [comment]
addressed with #88 (Debbie)
