### ISSUE TITLE
CNExT encounter occurrence and obs period may retrieve start/end of Tx and first date of Dx

### ISSUE THREAD

**Issue by isangil** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#21]

**Comment by lvarnedoe** [comment]
After speaking with Auvergne today, I believe we would want to include first date of contact over first date of Dx.

**Comment by markmayer** [comment]
Agree

**Comment by lvarnedoe** [comment]
Changed OBSERVATION_PERIOD_START_DATE to the date of first contact with the patient and changed OBSERVATION_PERIOD_END_DATE to the date of last contact with patient or death.

**Comment by lvarnedoe** [comment]
The above done in cnext_observation_period script. May also change in cnext_visit_occurrence. Waiting for comment bf doing that.

**Comment by isangil** [comment]
addressed with #117
