### ISSUE TITLE
CNExT - Conditions on Radiation Table Differ From Script to Script

### ISSUE THREAD

**Issue by lvarnedoe** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#57]
In the cnext_device_exposure script, the condition on the Radiation table is:
WHERE F05257 > '000'            --F05257 = Radiation, Number of Treatments
    AND RAD.F07799 > '00'      --F07799 = Radiation, Treatment Modality
    AND RAD.F07799 < '99'

Per Mark: The rationale behind RAD.F07799 NOT IN ('00', '99') is that we only want to capture when radiation tx is done so kicking out 00 - No rad tx and 99 - unknown. Putting in the '' in the IN statement takes care of where there are no values (or it's NULL) for RAD.F07799 which we do not want ...

Handled where F07799 is NULL, empty, equal to '00', or equal to '99' by changing condition to F07799 > '00' and F07799 < '99'.

In cnext_procedure_occurrence, the condition is only:
WHERE F07799 > '00'
    AND F07799 < '99'                      Shouldn't  F05257 > '000' also be in the condition?

In cnext_visit_detail, the condition is only:
WHERE F05257 > '000'                   Shouldn't AND F07799 > '00' AND F07799 < '99' also be in the condition?

**Comment by markmayer** [comment]
Yes, all of these queries should have the same filter criteria 

WHERE F05257 > '000' Shouldn't AND F07799 > '00' AND F07799 < '99'

**Comment by lvarnedoe** [comment]
These queries have been updated, but I'm having trouble with the P drive from home, so can't upload today. Will try tomorrow.

**Comment by lvarnedoe** [comment]
addressed with Change conditions on Radiation table #57
