### ISSUE TITLE
CNExT - cnext_procedure_occurrence Possibly Missing Information

### ISSUE THREAD

**Issue by lvarnedoe** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#63]
I would think a transplant would be a procedure occurrence.

**Comment by lvarnedoe** [comment]
Also, the OMOP CDM description reads:
This table contains records of activities or processes ordered by, or carried out by, a healthcare provider on the patient with a diagnostic or therapeutic purpose.
Should chemo, radiation, immuno-therapy, etc... be included also?

**Comment by lvarnedoe** [comment]
Sorry, radiation is included, so should chemo, immuno-therapy, and hormone therapy also be included?

**Comment by markmayer** [comment]
After thinking about this and the overall OMOP model, I agree we should include all of those activities, even though some are captured in other tables (I.E., DRUG_EXPOSURE etc). If there is duplication, we can deal with it within the OMOP framework.

**Comment by lvarnedoe** [comment]
Addressed.
