### ISSUE TITLE
CNExT - Should cnext_measurement Include Tumor Marker Information?

### ISSUE THREAD

**Issue by lvarnedoe** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#64]
OMOP CDM describes the measurement table as:

The MEASUREMENT table contains records of Measurements, i.e. structured values (numerical or categorical) obtained through systematic and standardized examination or testing of a Person or Person’s sample. The MEASUREMENT table contains both orders and results of such Measurements as laboratory tests, vital signs, quantitative findings from pathology reports, etc. 

According to the SME, the only labs in cnext relate to a patient's tumor/cancer and are recorded as tumor markers. Should these be included in the select statement? I found them in the tumor table.

**Comment by markmayer** [comment]
Yes, please include.

**Comment by lvarnedoe** [comment]
We have reviewed the possibility of adding tumor markers and have decided against it. 95% of the records (as of 3/3/22 60,894 out of 64,282) in the Tumor table have 9's as the value for Tumor Marker 1, Tumor Marker 2, and Tumor Marker 3, which equates to "Unknown", so it doesn't seem worthwhile to include the few records that do have values, and even some of those records have values that signify "Range 2 with no other information (Not collected since 2002)". 
Auvergne confirmed the following values for me:
0 = Not done
1 = Positive/Elevated
2 = Negative/Normal
4 & 5 = Range 2 with no other information (Not collected since 2002)
9 = Unknown
