### ISSUE TITLE
CNExT - Should Conditions on the Surg Table be Changed?

### ISSUE THREAD

**Issue by lvarnedoe** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#65]
Currently, the conditions on the Surg table read like this:

SRG.F03488 != '00' 
AND SRG.F03488 < '98'

Would it be better to write it as:
SRG.F03488 > '00'
AND SRG.F03488 < '98'

The latter will prevent empty space and NULL values from being returned.

The change would affect cnext_visit_detail and cnext_procedure_occurrence.

**Comment by markmayer** [comment]
Yes, agree. Please use

SRG.F03488 > '00'
AND SRG.F03488 < '98'

**Comment by lvarnedoe** [comment]
Changed in both scripts per Mark.

**Comment by lvarnedoe** [comment]
addressed.
