### ISSUE TITLE
(High)CNExT - PERSON_ID Is Not Pulled From Same Table Consistently

### ISSUE THREAD

**Issue by lvarnedoe** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#66]
PERSON_ID is pulled from:
Hospital.F00006    --Medical Record Number

Hospital.F00016    --Accession Number
   selected as:
                   SELECT TOP 1 rsTarget.F00016 FROM Hospital rsTarget WHERE rsSource.uk = rsTarget.fk2  Order By rsTarget.UK ASC
          and as:
                   HSP.F00016
PatExtended.F00004    --Patient ID Number
   selected as:
                   SELECT TOP 1 rsTarget.F00004 FROM PatExtended rsTarget WHERE rsTarget.uk =  rsSource.fk1 Order By rsTarget.UK ASC
          and as:
                  PatExtended.F00004 

Shouldn't it be the same across the board?

**Comment by markmayer** [comment]
Since we are now attaching MRN to the end of all of the extracts, I'm wondering if PERSON_ID should all be Accession Number? Maybe feedback or a discussion is necessary.

**Comment by KJDonovan-RS21** [comment]
Patient Id needs to be consistent across all extracts from each source system.

**Comment by markmayer** [comment]
OK, let's map all instances of PERSON_ID to MRN.

**Comment by lvarnedoe** [comment]
Okay, Mark. I’ve been seeing your responses to the issues I opened. I can get everything done when I get back. I’ll be in Monday.
Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lvarnedoe** [comment]
PERSON_ID was changed to consistently come from the Patient table's uk throughout the cnext scripts.
