### ISSUE TITLE
CNExT - Conditions on Chemo Table Differ From Script to Script

### ISSUE THREAD

**Issue by lvarnedoe** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#67]
cnext_drug_exposure conditions on Chemo table are:
           CHM.F05037 IN ('01', '02', '03')      --Chemotherapy, Procedure
   AND CHM.F05669 > '00'                       --Chemotherapy, Course
   AND CHM.F04755 is not null                 --Chemotherapy, NSC Number

cnext_visit_detail:
            CHM.F05037 IN ('01', '02', '03')
    AND CHM.F05669 > '00'

Should cnext_visit_detail's conditions match cnext_drug_exposure's conditions?

**Comment by markmayer** [comment]
Please delete the line

AND CHM.F04755 is not null 

from cnext_drug_exposure

**Comment by lvarnedoe** [comment]
Removed line per Mark.

**Comment by lvarnedoe** [comment]
addressed on Change conditions on Chemo tbl in script #67
