### ISSUE TITLE
(High) CNExT provider ID funk

### ISSUE THREAD

**Issue by isangil** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#73]
Expect numerics, get

PROVIDER_ID
--
18-0028
2018-062
...
3% records.  may not be a severe thing

**Comment by KJDonovan-RS21** [comment]
Does not matter data type of provider id, but needs to correlated with other extracts for RI.

**Comment by isangil** [comment]
i think this is fixed by Mark's LDS data type adaptation
