### ISSUE TITLE
(High) Mosaiq.Measurement.UNIT_SOURCE_VALUE - Need Code Descriptions Too

### ISSUE THREAD

**Issue by KJDonovan-RS21** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#84]
Mosaiq.Measurement.UNIT_SOURCE_VALUE appears to us a non-standard vocabulary, so I need a valid list of codes and descriptions so I can look up the associated OMOP concept code.

**Comment by isangil** [comment]
Fixed by sending custom mapping by spreadsheet
