### ISSUE TITLE
Mosaiq Notes isNULL(NTE.Create_ID,'')  AS PROVIDER_ID may have nulls

### ISSUE THREAD

**Issue by dahealy** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#90]
I added Create_ID as Provider_ID to identify notes created by MDs - but may contain administrative/tech people

**Comment by dahealy** [comment]
Provider_ID = Create_ID :may be the MD/APP/Nurse or administrative person who created the note -- OR IT MAY BE NULL
OPTION (so there will be orphans)
1)  Don't fill in Provider_ID
2)  Understand that there will be orphans
3)  Concatenate Provider_ID at the beginning of the NOTE

ALSO:  Should note be in field NOTE_SOURCE_VALUE or in NOTE_TEXT?  Too much data to be in both.  Mike prefers _VALUE fields to be populated as completely as possible)

**Comment by isangil** [comment]
I heard we can just leave it null (as in ''), as it does not compromise the integrity.  So option 1 @dahealy

**Comment by isangil** [comment]
ill take this @dahealy
