### ISSUE TITLE
CNExT: Date field formatting - All Extracts

### ISSUE THREAD

**Issue by markmayer** [UNMCCC/CRIIS_Source_Extracts_for_OMOP#96]
Please format all DATE fields as YYYY-MM-DD HH24:MI:SS. This is for all extracts.

**Comment by lvarnedoe** [comment]
I don't see any times other than 00:00:00, so is there a need to put these on a 24 hour clock? It doesn't appear that CNExT concerns themselves with exact times, just dates.

**Comment by lvarnedoe** [comment]
Actually, the datetime fields are already on the 24 hour clock. Apparently, in SSMS  the 24 hour clock is identified by the capital H's in the time. HH:mm:ss would be on the 24 hour clock while hh:mm:ss is on the 12 hour one. So the datetime fields should all already be correct.

**Comment by markmayer** [comment]
Yeah, just to be consistent. All date fields should be 24 hr clock.

**Comment by lvarnedoe** [comment]
I am saying that they already are on a 24 hour clock, so this isn't an issue with the cnext extracts.

**Comment by lvarnedoe** [comment]
I'm going to close this issue, since I don't think it is one based on the info I found on formatting in SSMS.
